// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfOYTGRsBbB5_pfe_tHhVNgEUGXzOqGl8',
    appId: '1:622500055950:web:4e4a02f27eb04dd3dd32df',
    messagingSenderId: '622500055950',
    projectId: 'isef-68b63',
    authDomain: 'isef-68b63.firebaseapp.com',
    storageBucket: 'isef-68b63.appspot.com',
    measurementId: 'G-9TEEBFCM9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3hkWHYcwF-J3hXP3Z3tR6eX6bPjXt8-A',
    appId: '1:622500055950:android:09797ea5e3d1b909dd32df',
    messagingSenderId: '622500055950',
    projectId: 'isef-68b63',
    storageBucket: 'isef-68b63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnFSTzKUowSCPwMq-Dfpx0cd5gls-WFWM',
    appId: '1:622500055950:ios:ebb7dc660efaa671dd32df',
    messagingSenderId: '622500055950',
    projectId: 'isef-68b63',
    storageBucket: 'isef-68b63.appspot.com',
    iosClientId: '622500055950-bbkhdlbtrci9nd0sv7oej3qm2i01ii2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.webAdminIsef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnFSTzKUowSCPwMq-Dfpx0cd5gls-WFWM',
    appId: '1:622500055950:ios:630f33b774589f96dd32df',
    messagingSenderId: '622500055950',
    projectId: 'isef-68b63',
    storageBucket: 'isef-68b63.appspot.com',
    iosClientId: '622500055950-iein32hkrfo0rj2136p8salv7m39g3qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.webAdminIsef.RunnerTests',
  );
}
